// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx ts-node prisma/seed-workflow.ts",
  },
  datasource: {
    // Fallback for prisma generate (doesn't connect); runtime uses real DATABASE_URL from env
    url: process.env.DATABASE_URL ?? "postgresql://localhost:5432/syncro",
  },
});
